# Generated by Django 4.2 on 2023-12-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objave', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objava',
            options={'ordering': ['-id']},
        ),
    ]
